Algoritmo "atvlista56"
//  
//  


Var
   n,soma,contagem: inteiro


Inicio
   contagem <-0
   escreval ("USE 1111 PARA FINALIZAR")
   escreval ("--------------------------")
   enquanto ( n <> 1111)faca
      escreval (" digite um numero:")
     	leia(n)
      se (n <> 1111)entao
         soma <- soma + n
      fimse
   fimenquanto

   escreval ("soma:",soma)



fimalgoritmo