algoritmo "Distancia"
var
M,K,H,Da,Dm,Cm,MM:real
inicio
      escreva("Digite uma distancia em metros: ")
      leia(M)
      K<-M/1000
      H<-M/100
      Da<-M/10
      Dm<-M*10
      Cm<-M*100
      MM<-M*1000
      escreval(" ")
      escreval("Distancia em Km: " ,K)
      escreval("Distancia em Hm:  ",H)
      escreval("Distancia em Da: ",Da)
      escreval("Distancia em Dm  ",Dm)
      escreval("Distancia em Cm: ",Cm)
      escreval("Distancia em MM: ",MM)
fimalgoritmo