algoritmo "semnome"
var
   frase: caractere
   contador: inteiro
   
procedimento aprendendoPortugol (fraseCerta: caractere)
inicio

   leia (fraseCerta)
   limpatela
   
   escreval ("=====-----+++++-----=====")
   para contador <- 1 ate 4 faca
   escreval (fraseCerta)
   fimpara
   escreval ("=====-----+++++-----=====")

fimprocedimento
inicio
   escreval ("DIGITE UMA FRASE")
   aprendendoPortugol (frase)


   

fimalgoritmo