Algoritmo "T4_exercicio_1"
//
//
// Descrição   : exercicio do lab: contador que conta de 5 ate 11
// Autor(a)    : Nielon cardoso dos reis
// Data atual  : 23/5/2024
Var
// Seção de Declarações das variáveis
 contador :inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   contador <-5
   enquanto (contador<=11) faca
    escreval(contador)
    contador <-contador+1
   fimenquanto

Fimalgoritmo