Algoritmo "T4_exercicio_3"
//
//
// Descrição   : exercicio do lab: contador que conta de 3 em 3
// Autor(a)    : Nielon cardoso dos reis
// Data atual  : 23/5/2024
Var
// Seção de Declarações das variáveis
 contador :inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("contador:")
   contador <-0
   enquanto (contador<=18) faca
    escreva(contador,",")
    contador <-contador+3
   fimenquanto
   escreval("Acabou!!")
Fimalgoritmo