Algoritmo "T4_exercicio_2"
//
//
// Descrição   : exercicio do lab: contador que conta de 11 a 3
// Autor(a)    : Nielon cardoso dos reis
// Data atual  : 23/5/2024
Var
// Seção de Declarações das variáveis
 contador :inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   contador <-11
   enquanto (contador>=3) faca
    escreva(contador,",")
    contador <-contador-1
   fimenquanto
   escreval("Acabou!!")
Fimalgoritmo