algoritmo "88Lista"
var
   frase: caractere

procedimento aprendendoportugol (frasecerta: caractere)
inicio

   leia (fraseCerta)
   limpatela
   escreval ("+-------=======------+")
   escreval (frasecerta)
   escreval (frasecerta)
   escreval (frasecerta)
   escreval (frasecerta)
   escreval ("+-------=======------+")

fimprocedimento
inicio
   escreval ("DIGITE UMA FRASE")
   aprendendoportugol (frase)


fimalgoritmo