Algoritmo "atvlista69"

Var
   t,razao,contagem,soma,termo,decimot:inteiro
   


Inicio
      escreva("Digite o primeiro termo:")
      leia(t)
      escreva("Digite a razao:")
      leia(razao)
      decimot <- t+(10-1)*razao
        para contagem de termo ate decimot passo razao faca
        escreval (contagem)
        soma <- soma+contagem

        fimpara
      escreval("SOMA:",soma)
Fimalgoritmo