algoritmo "11Lista"
var
a,b,c,delta, d1,d2:real
inicio
Escreva("Escreva o valor de A: "
Leia(a)
Escreva("Escreva o valor de B: "
Leia(b)
Escreva("Escreva o valor de C: "
 delta<- (-b * -b) - (4 * a*c)
 d1 <- (-b + Raizq(delta)) / (2*a)
 d2 <- (-b - Raizq(delta)) / (2*a)
 Escreval (" ")
 Escreva ("o valor de delta", delta)
 Escreval(" ")
 Escreva("valor de x1: ", d1)
 Escreva("valor de x2: ", d2)
 
 
fimalgoritmo