algoritmo "12Lista"
var
Valor:Real
Nome:caractere
Des:Real
total:Real
inicio
Escreval("BEM VINDO A PLIM")
Nome<- ("Conchinha")
Escreval("Escreva o valor da ", Nome, ":")
Leia(Valor)
Des<- (Valor*15/100)
Escreval("PARABENS VOCE CONSEGUIU DESCONTO!!")
Escreval("O valor do desconto e", Des, "!")
total<-Valor-Des
Escreval("Total do valor da ", Nome," e: ", Valor)
Escreval("Agora com desconto por apenas ", total, "!!!")
fimalgoritmo