Algoritmo "97Lista"
// 
//  
// Descrição   : Maior
// Autor(a)    : Thales Jose de Oliveira
// Data atual  : 15/7/2024
Var
numero2, A:inteiro
funcao maior (numero:inteiro): inteiro
inicio
 enquanto (numero <> 1111) faca
    escreval("Vamos mais 1 ")
    leia(numero)


    se (numero > numero2) entao
   escreval("o numero ", numero," e o maior")
   fimse
   fimenquanto
fimfuncao

Inicio
  escreval("digite ")
  leia(numero2)
A <- maior (numero2)

Fimalgoritmo