Algoritmo "T7_exercicio_2"
//
//
// Descrição   : exercicio do lab: exercicio 65
// Autor(a)    : Nielon cardoso dos reis
// Data atual  : 23/5/2024
Var
   // Seção de Declarações das variáveis
   cont :inteiro
Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   para cont <-100 ate 0 passo -10 faca
    escreva(cont,",")
   fimpara
   escreval("")
   escreval("Acabou!!!!!")
Fimalgoritmo