Algoritmo "T7_exercicio_4"
//
//
// Descrição   : exercicio do lab:  exercico numero 67
// Autor(a)    : Nielon cardoso dos reis
// Data atual  : 23/5/2024
Var
// Seção de Declarações das variáveis
cont, numero :inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
  escreval("digite o numero final da contagem ")
  leia(numero)
   para cont <- 0 ate numero passo 1 faca
    escreva(cont,",")
   fimpara
  escreval(" FIM ")

Fimalgoritmo