Algoritmo "56Lista"
// Autor(a)    : Thales Oliveira
// Data atual  : 26/6/2024
Var
numero1, numero2, total:inteiro

Inicio
    enquanto (numero2 <> 1111) faca
    escreval("Vamos somar escreva um numero ")
    leia(numero1)
    escreval("Outro numero" )
    leia (numero2)
    se(numero1 e numero2<>1111) entao
    total<- numero1 + numero2
       escreval(total)
       fimse
    fimenquanto
Fimalgoritmo