Algoritmo "56Lista"
// Autor(a)    : Thales Oliveira
// Data atual  : 26/6/2024
Var
numero1, numero2, total:inteiro

Inicio
    enquanto (numero2 <> 1111) faca
    escreval("Vamos somar escreva um numero ")
    leia(numero1)
    escreval("Outro numero" )
    leia (numero2)
    total<- numero1 + numero2
       escreval(total)
       se(numero1 e numero2 =1111) entao
        escreval("fechado")
        fimse
        fimenquanto
Fimalgoritmo