Algoritmo "58Lista"
Var
   idade,totalidade,total:inteiro
   m:real

Inicio
      enquanto (idade <> 999) faca
          escreva("Sua Idade:")
             leia (idade)
          se (idade <> 999)entao
            total <- total+1
            totalidade<-totalidade + idade
            m <- totalidade/total
          fimse
      fimenquanto


 escreval("Total de pessoas: ", total)
 escreva("Media das idades: ", m: 5:0)

Fimalgoritmo