Algoritmo "atvlista91"

Var
n1,n2,n:inteiro
procedimento maior
inicio
   se (n1= n2)entao
      escreva("VALORES IGUAIS")
   senao
      se(n1>n2) entao
         escreva("MAIOR NUMERO:", n1)
      senao
            se (n1<n2) entao
               escreva("MAIOR NUMERO:", n2)
            fimse

      fimse
   fimse
      

fimprocedimento
Inicio
   escreva("Numero:")
   leia(n1)
   escreva("Numero:")
   leia(n2)
   maior



Fimalgoritmo