Algoritmo "T9_exercicio_2"
//
//
// Descrição   : exercicio do lab: procedimento personalizado  exercicio 87
// Autor(a)    : Nielon cardoso dos reis
Var
   // Seção de Declarações das variáveis
   text:caractere
Procedimento texto
Inicio

   escreval("<----------->")
   escreval("<--",text,"-->")
   escreval("<----------->")
fimprocedimento

inicio
   escreva("digite algo")
   leia(text)
   texto
Fimalgoritmo