Algoritmo "atvlista28"
//  
//  

Var
 com, lg, mq: real


Inicio
escreva ("digite o comprimento do terreno:")
leia (com )
escreva ("digite a largura do programa:")
leia (lg)
mq <- (com*lg)
 escreval ("o terreno tem", mq, "metros quadrados:")
 se (mq < 100)entao
 escreva ("terreno popular")
 senao
 se ( mq>=100) e (mq<=500)entao
 escreva ("terreno master")
 senao
 se (mq>500)entao
 escreva ("terreno vip")
 fimse
 fimse
 fimse
 



Fimalgoritmo