Algoritmo "Exercicio 26"

Var
   N1,N2:inteiro


Inicio
   escreva("Digite um numero inteiro:")
   leia(N1)
   escreva("Digite outro numero inteiro:")
   leia(N2)
   se N1>N2 entao
      escreva("O primeiro numero é maior")
   senao
      se  N2>N1 entao
         escreva("O segundo numero é maior.")
      senao
         se N1=N2 entao
            escreva("Os dois numeros tem valores iguais.")
         fimse
      fimse
   fimse


Fimalgoritmo