algoritmo "semnome"

var

A, B,resultado,primeiro, segundo,total: real

Funcao total(A, B: real):real

inicio
      retorne primeiro^segundo
fimfuncao

inicio

   EscrevaL("Escreva o valor base")

   leia(primeiro)

   EscrevaL("Escreva o valor do expoente")

   leia(segundo)

   resultado <- total(primeiro,segundo)

   escreva("O RESULTADO FOI: ",resultado)

fimalgoritmo