Algoritmo "T2_exercicio_4"
//
//
// Descrição   : descubra se um numero é impar ou par
// Autor(a)    : Nielon cardoso dos reis
// Data atual  : 29/5/2024
Var
// Seção de Declarações das variáveis
n1, mo   :real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval(" digite um numero " )
leia(n1)
mo <- (n1%2)
se (mo <> 0) entao
         escreval("este numero é impar")
senao
     escreva("este numero é par ")
fimse
Fimalgoritmo
