Algoritmo "T2_exercicio_5"
//
//
// Descrição   : descubra se o ano é bisexto
// Autor(a)    : Nielon cardoso dos reis
// Data atual  : 29/5/2024
Var
// Seção de Declarações das variáveis
ano, m :real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("digite um ano: ")
leia(ano)
m <- (ano%4)
se (m <> 0) entao
                 escreva("esse ano não é bisexto")
senao
     escreva ("essa ano é bisexto")
fimse





Fimalgoritmo
