algoritmo "exercicio7"
var
   Nome:caractere
   Ano:inteiro
   To:inteiro
inicio
   eSCREVAL( "Martins vilela")
   Escreva("Seu nome: ")
   Leia(Nome)
   Escreva("Qual seu ano de nascimento: ")
   Leia(Ano)
   To<-2024-Ano
   se(To>=18) entao
      Escreval(Nome, "Voce pode se habilitar-se!")
   senao
      Escreva(Nome, ", Voce nao pode se habilitar, voce tem ", To,"!")
   Fimse
fimalgoritmo