algoritmo "Video4"
var
  A, B, C, D, X, F: Inteiro
inicio
 Escreva("Digite um numero: ")
 Leia(A)
 Escreva("Digite novamente: ")
 Leia(B)
 Escreva("Digite novamente: ")
 Leia(C)
 Escreva(A, " e ", B, , C,"Serao")
 Escreva ((A<B) e (C=A))
 Escreva(" Digite um numero: ")
 Leia(D)
 Escreva("Digite novamente: ")
 Leia(X)
 Escreva("Digite novamente: ")
 Leia(F)
 Escreva ((X<F) ou (D=D))

fimalgoritmo