algoritmo "46Lista"
var
soma, total, seis:inteiro
contador:inteiro
inicio
contador<-6
enquanto (contador<=100) faca
     escreva(contador)
     contador<-contador+2
     escreva()
fimenquanto
//
total<-0

para soma de 6 ate 100 faca
    se ((soma mod 2) <> 1) entao
    total <- total + soma
    fimse
fimpara
escreval
escreval(" A soma dos numeros de 6 ate 100 eh: ", total)
fimalgoritmo