algoritmo "46Lista"
var
soma, total, seis:inteiro
contador:inteiro
inicio
contador<-0
enquanto (contador<=500) faca
     escreva(contador)
     contador<-contador+50
     escreva()
fimenquanto
//
total<-0

para soma de 500 ate 0 passo -50 faca
    se ((soma mod 2) <> 1) entao
    total <- total + soma
    fimse
fimpara
escreval
escreval(" A soma dos numeros de 500 ate 0 eh: ", total)
fimalgoritmo