algoritmo "48Lista"
var
soma, total:inteiro
contador, final:inteiro
inicio
escreval("digite um numero")
leia(contador)
escreva("digite o numero final")
leia(final)
enquanto (contador<=final) faca
     escreva(contador)
     contador<-contador+1
     escreva()
fimenquanto
//
contador<- contador +1

   

escreval
escreval(" A soma dos numeros de", contador," ate ", final, " eh: ", contador)
fimalgoritmo