Algoritmo "video6_imposto americanp"
// 
//  
// Descrição   : ajudando creuza a analisar imposto
// Autor(a)    : Nielon cardoso dos reis
// Data atual  : 27/5/2024
Var
// Seção de Declarações das variáveis 
preco, imposto :real



Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("insira o preço do produto")
leia(preco)
imposto <- (preco*60)/100
escreval("o valor que vc devera pagar com impostos inclusos é :",imposto+preco)


Fimalgoritmo