Algoritmo "atvlista49"
//  
//  

Var
 n,contagem , par, impar:inteiro

Inicio
 contagem <-1
 par <-0
 impar <-0
 enquanto (contagem <=6)faca
 contagem <-contagem +1
 escreva ("digite um numero:")
 leia (n)
   se (n % 2 =0)entao
     par <- par+1
   senao
      impar <-impar+1
      fimse
      fimenquanto


 escreval("numeros pares:",par:1)
 escreval("numeros impares:",impar:1)





Fimalgoritmo