algoritmo "18Lista"
var
datnasc:inteiro
nasc:Inteiro
Ano:inteiro
inicio
 Escreval("Opaa em que ano voce nasceu garota(o)?")
 Leia(nasc)
 Escreval("Vim do fututo.. em que ano estamos?")
 Leia(Ano)
 datnasc<-Ano-nasc
 Escreval(datnasc)
 Se(datnasc>=16) entao
 Escreval("Voce tem ", datnasc," pode votar no senhor galinho.")
 senao
 Escreval("Voce nao vai votar no senhor galinho para salvar o futuro")
 fimse
fimalgoritmo