Algoritmo "atvlista74"

Var
   v:vetor[0..9] de inteiro
   contagem:inteiro
   c:logico
   valor :inteiro
Inicio
      c <- verdadeiro
      para contagem de 0 ate 9 faca
      se (c = verdadeiro) entao
         valor <- 5
         c<- falso
      senao
       valor <-3
       c<- verdadeiro
      fimse
         v[contagem]<- valor

      fimpara
       para contagem de 0 ate 9 faca
        escreva(v[contagem])
        fimpara



Fimalgoritmo