Algoritmo "atvlista75"

Var
contagem:inteiro
v:vetor[1..15] de inteiro
n1, n2 , n3: inteiro


Inicio
   n1<- 0
   escreva (n1)
   n2 <-1
         escreva (n2)

   para contagem de 3 ate 15 faca
      v[contagem] <- n1+ n2
         n1 <- n2
         n2 <- v[contagem]
         v[contagem] <- v[contagem]
         escreva (v[contagem])
   fimpara






   
   
   
Fimalgoritmo