algoritmo "Contador"
var
   contador, numero: inteiro
inicio
      escreval ("Escolha um numero inteiro e o computador ira contar ate ele:")
      escreva ("Numero escolhido: ")
      leia (numero)
      contador <- 0
      Enquanto (contador <= numero) faca
               escreval (contador)
               contador <- contador + 1
      fimenquanto
      escreval ("ACABOU")
Fimalgoritmo