algoritmo "Exercicio 96"

var

   n1,n2,m:real

funcao media(a,b:real):real
inicio
   retorne (a+b)/2




fimfuncao



inicio

   Escreval("Média aluno")

   escreval("------------")

   escreval("Qual a primeira nota do aluno?")

   leia(n1)

   escreval("Qual a segunda nota do aluno?")

   leia(n2)

   m<-media(n1,n2)

   escreval("A média de nota dele foi:",m)



fimalgoritmo
