Algoritmo "T8_exercicio_3"
//
//
// Descrição   : exercicio do lab: de 9 a zero
// Autor(a)    : Nielon cardoso dos reis
// Data atual  : 23/5/2024
Var
   // Seção de Declarações das variáveis
   v:vetor[0..9] de inteiro
   c,numero:inteiro
Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   numero <- 9
   para c <- 0 ate 9 passo 1 faca
    escreva(numero,",")
     numero <- numero-1
   fimpara
Fimalgoritmo