Algoritmo "exercicio_7"
//
//
// Descrição   : exercicio do lab: leia um numero real e mostre seu dobro e seu terço
// Autor(a)    : Nielon cardoso dos reis
// Data atual  : 23/5/2024
Var
// Seção de Declarações das variáveis
n1 :real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("digite um numero real")
leia(n1)
escreval("o dobro de" ,n1," é ",n1*2)
escreval("um terço de " ,n1," é ",n1/3)

Fimalgoritmo