Algoritmo "exercicio_6"
//
//
// Descrição   : exercicio do lab: leia um numero e mostre seu sucessor e antecessor
// Autor(a)    : Nielon cardoso dos reis
// Data atual  : 23/5/2024
Var
// Seção de Declarações das variáveis
n1 :inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("digite um numero inteiro: ")
leia(n1)
escreval("o sucessor de ",n1," é ",n1+1)
escreval("o antecessor de ",n1," é ",n1-1)

Fimalgoritmo