Algoritmo "exercicio_11"
//
//
// Descrição   : exercicio do lab: leia os valores de A,B,C e ache o delta
// Autor(a)    : Nielon cardoso dos reis
// Data atual  : 23/5/2024
Var
// Seção de Declarações das variáveis
a,b,c ,d :real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva(" o valor de A ")
leia(a)
escreva("o valor de B ")
leia(b)
escreva("o valor de C ")
leia(c)
d <-(b^2-4*a*c)
escreval("o delta desta equação é ",d)

Fimalgoritmo