Algoritmo "exercicio_9"
//
//
// Descrição   : exercicio do lab: transforme real em dolares
// Autor(a)    : Nielon cardoso dos reis
// Data atual  : 23/5/2024
Var
// Seção de Declarações das variáveis
n1, n2 :real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("quantos reais vc tem na carteira ?: ")
leia(n1)
escreval(n1," reais dá aproximadamente em dolar ",n1/3.45)

Fimalgoritmo