Algoritmo "exercicio_13"
//
//
// Descrição   : exercicio do lab:crie um programa que leia um salario de um funcionario e mostre seu aumento
// Autor(a)    : Nielon cardoso dos reis
// Data atual  : 23/5/2024
Var
// Seção de Declarações das variáveis
n1, n2, n3 :real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("o valor do seu salario")
leia(n1)
n2 <-n1/100
n3 <- n1+(n2*15)
escreval(" o preço com o aumento fica :",n3," reais")

Fimalgoritmo