Algoritmo "exercicio_8"
//
//
// Descrição   : exercicio do lab: transforme metro em outras medidas
// Autor(a)    : Nielon cardoso dos reis
// Data atual  : 23/5/2024
Var
// Seção de Declarações das variáveis
m :real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("digite uma distancia em metros: ")
leia(m)
escreval(" isso em hectometros dá ",m/100,"hm")
escreval(" isso em kilometros dá ",m/1000,"km")

Fimalgoritmo