Algoritmo "exercicio_12"
//
//
// Descrição   : exercicio do lab:  leia  o preço  de um produto calcule e mostre seu preço promocional
// Autor(a)    : Nielon cardoso dos reis
// Data atual  : 23/5/2024
Var
// Seção de Declarações das variáveis
n1, n2, n3 :real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("o valor do seu produto")
leia(n1)
n2 <-n1/100
n3 <- n1-(n2*15)
escreval(" o preço com a promoção fica :",n3," reais")

Fimalgoritmo