Algoritmo "exercicio_4"
//
//
// Descrição   : exercicio do lab: crie um programa que le dois numeros e some eles
// Autor(a)    : Nielon cardoso dos reis
// Data atual  : 23/5/2024
Var
// Seção de Declarações das variáveis
n1, n2 :real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("digite um numero para a soma: ")
leia(n1)
escreva("digite outro numero: ")
leia(n2)
escreva(" a soma de ",n1," e ",n2," dá no total ",n1+n2)

Fimalgoritmo